version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/db:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"               # ánh xạ port để pgAdmin và host có thể kết nối


  odoo:
    image: odoo:16.0
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8069"
    volumes:
      - ./volumes/odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf:ro


  # pgadmin:
  #   image: dpage/pgadmin4:7
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@domain.com
  #     PGADMIN_DEFAULT_PASSWORD: secret
  #   ports:
  #     - "8081:80"                 # truy cập pgAdmin tại http://localhost:8081
  #   volumes:
  #     - ./volumes/pgadmin:/var/lib/pgadmin
  #   depends_on:
  #     - db
